// 第十章代码

// 选择一个，注释掉其他的
//#define CHAPTER_10_10_6
//#define CHAPTER_10_CAMERA
//#define CHAPTER_10_EXERCISE_1
//#define CHAPTER_10_EXERCISE_2
//#define CHAPTER_10_EXERCISE_3
//#define CHAPTER_10_EXERCISE_4
//#define CHAPTER_10_EXERCISE_5
//#define CHAPTER_10_EXERCISE_6
//#define CHAPTER_10_EXERCISE_7
//#define CHAPTER_10_EXERCISE_8
//#define CHAPTER_10_EXERCISE_9
//#define CHAPTER_10_EXERCISE_10
//#define CHAPTER_10_EXERCISE_11
//#define CHAPTER_10_EXERCISE_12
//#define CHAPTER_10_EXERCISE_13
#define CHAPTER_10_EXERCISE_13_TEST


#ifdef CHAPTER_10_CAMERA
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_1
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_2
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_3
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_4
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_5
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_6
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_7
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_8
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_9
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_10
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_11
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_12
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_13
#define CHAPTER_10_COMMON
#endif

#ifdef CHAPTER_10_EXERCISE_13_TEST
#define CHAPTER_10_COMMON
#endif

//////////////////////////////////////////////////////////////////////////