// 第七章代码

// 选择一个，注释掉其他的
//#define CHAPTER_7_1_1 // 二维平移
//#define CHAPTER_7_1_2 // 二维旋转
//#define CHAPTER_7_1_3 // 二维缩放
//#define CHAPTER_7_4_11 // 二维复合矩阵
//#define CHAPTER_7_10 // OpenGL几何变换
//#define CHAPTER_7_EXERCISE_1
//#define CHAPTER_7_EXERCISE_2
//#define CHAPTER_7_EXERCISE_3
//#define CHAPTER_7_EXERCISE_4
//#define CHAPTER_7_EXERCISE_5
//#define CHAPTER_7_EXERCISE_6
//#define CHAPTER_7_EXERCISE_7
//#define CHAPTER_7_EXERCISE_8
//#define CHAPTER_7_EXERCISE_9
//#define CHAPTER_7_EXERCISE_10
//#define CHAPTER_7_EXERCISE_11
//#define CHAPTER_7_EXERCISE_12
//#define CHAPTER_7_EXERCISE_13
//#define CHAPTER_7_EXERCISE_14
//#define CHAPTER_7_EXERCISE_15
//#define CHAPTER_7_EXERCISE_16
//#define CHAPTER_7_EXERCISE_17
//#define CHAPTER_7_EXERCISE_18
//#define CHAPTER_7_EXERCISE_19
//#define CHAPTER_7_EXERCISE_20
//#define CHAPTER_7_EXERCISE_21
//#define CHAPTER_7_EXERCISE_22
//#define CHAPTER_7_EXERCISE_23
//#define CHAPTER_7_EXERCISE_24
//#define CHAPTER_7_EXERCISE_24_1 // 递归化简变换
//#define CHAPTER_7_EXERCISE_24_2 // 麻将递归
//#define CHAPTER_7_EXERCISE_25
//#define CHAPTER_7_EXERCISE_26
//#define CHAPTER_7_EXERCISE_27
//#define CHAPTER_7_EXERCISE_28
//#define CHAPTER_7_EXERCISE_29
//#define CHAPTER_7_EXERCISE_30
//#define CHAPTER_7_EXERCISE_31
//#define CHAPTER_7_EXERCISE_32
//#define CHAPTER_7_EXERCISE_ADD_1
#define CHAPTER_7_EXERCISE_ADD_2

#ifdef CHAPTER_7_1_1
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_1_2
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_1_3
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_4_11
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_10
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_1
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_2
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_3
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_4
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_5
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_6
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_7
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_8
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_9
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_10
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_11
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_12
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_13
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_14
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_15
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_16
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_17
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_18
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_19
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_20
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_21
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_22
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_23
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_24
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_24_1
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_24_2
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_25
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_26
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_27
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_28
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_29
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_30
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_31
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_32
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_ADD_1
#define CHAPTER_7_COMMON
#endif

#ifdef CHAPTER_7_EXERCISE_ADD_2
#define CHAPTER_7_COMMON
#endif